# Generated by Django 5.1.3 on 2024-11-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalSystem", "0003_personelloginlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="personelloginlog",
            name="is_late",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="personelloginlog",
            name="late_duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
