# Generated by Django 5.1.3 on 2024-11-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalSystem", "0006_personal_annual_leave_personal_total_late_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personal",
            name="annual_leave",
        ),
        migrations.AddField(
            model_name="personal",
            name="annual_leave_days",
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name="personal",
            name="annual_leave_hours",
            field=models.IntegerField(default=0),
        ),
    ]
