# Generated by Django 5.1.3 on 2024-11-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personalSystem", "0007_remove_personal_annual_leave_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("hours_used", models.FloatField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[("LATE", "Geç Kalma"), ("REQUEST", "İzin Talebi")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_usages",
                        to="personalSystem.personal",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
